// examples/solidjs/with-thirdpartyemailpassword/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web";
import { Router, Route } from "@solidjs/router";

import "./index.css";
import Auth from "./Auth";
import Dashboard from "./Dashboard";

const root = document.getElementById("root");

render(
    () => (
        <Router>
            <Route path="/dashboard" component={Dashboard} />
            <Route path="/auth/callback/google" component={Auth} />
            <Route path="/auth/callback/github" component={Auth} />
            <Route path="/auth/callback/apple" component={Auth} />
            <Route path="/" component={Auth} />
        </Router>
    ),
    root!
);

// examples/react/with-thirdpartyemailpassword/src/main.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import Auth from "./Auth.tsx";
import Dashboard from "./Dashboard.tsx";
import "./index.css";
import { createBrowserRouter, RouterProvider } from "react-router-dom";

const router = createBrowserRouter([
    {
        path: "/",
        element: <Auth />,
    },
    {
        path: "/auth/callback/*",
        element: <Auth />,
    },
    {
        path: "/dashboard",
        element: <Dashboard />,
    },
]);

createRoot(document.getElementById("root")!).render(
    <StrictMode>
        <RouterProvider router={router} />
    </StrictMode>
);
